
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/STD1_Maya_Berg150312.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/STD1_Maya_Berg150312.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Gray_Steph_13032012.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Gray_Steph_13032012.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/Std1_Ivana_29_2_12.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/Std1_Ivana_29_2_12.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Iain_Jonstone19_4_12.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Iain_Jonstone19_4_12.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/Std1_ROBELLO_Tcruzi002.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/Std1_ROBELLO_Tcruzi002.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Isabel_170512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Isabel_170512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Isabel_280512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Isabel_280512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Beer_esi_02022012.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Beer_esi_02022012.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Robello040512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Robello040512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Beth090512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Beth090512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Seattle_10_2_12.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Seattle_10_2_12.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Beth20512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Beth20512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Steph19_4_12.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Steph19_4_12.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Eileen02512.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Eileen02512.signal
java -ea -cp .:/Library/Frameworks/R.framework/Versions/3.1/Resources/library/mzmatch.R/java/mzmatch_2.0.jar GetSignals /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/std1_Thomas_Pfau.peakml /Users/simon/Dropbox/BioResearch/Meta_clustering/JoeDataProcessing/All_Standards/std1/pos/csv/std1_Thomas_Pfau.signal
